FROM ubuntu:jammy

EXPOSE 5000

ENV ASPNETCORE_ENVIRONMENT="Production"
ENV ASPNETCORE_URLS="http://*:5000"

RUN \
  apt-get -y update && \
  apt-get -y install \
  apt-utils \
  wget \
  apt-transport-https \
  unzip \
  acl \
  libssl1.0

RUN \
  apt-get -y install aspnetcore-runtime-8.0

RUN \
  adduser --disabled-password --gecos '' -u 2001 borderlink && \
  mkdir -p /var/www/borderlink && \
  mkdir /config && \
  wget -q https://github.com/immense/Remotely/releases/latest/download/BorderLink_Server_Linux-x64.zip && \
  unzip -o BorderLink_Server_Linux-x64.zip -d /var/www/borderlink && \
  rm BorderLink_Server_Linux-x64.zip && \
  chown -R borderlink:borderlink /var/www/borderlink

RUN \
  mkdir -p /borderlink-data && \
  sed -i 's/DataSource=BorderLink.db/DataSource=\/borderlink-data\/BorderLink.db/' /var/www/borderlink/appsettings.json && \
  chown -R borderlink:borderlink /borderlink-data

VOLUME "/borderlink-data"

WORKDIR /var/www/borderlink

COPY DockerMain.sh /

RUN chmod 755 /DockerMain.sh

USER borderlink

ENTRYPOINT ["/DockerMain.sh"]
